### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by JestySam** [Tervis-Tumbler/CUCMPowerShell#4]
Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
At D:\Pstest\CUCMPowerShellnew.psm1:211 char:5
+     $WebResponse = $WebRequest.GetResponse()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by ChrisMagnuson** [comment]
[This ](https://github.com/Tervis-Tumbler/CUCMPowerShell/blob/master/CUCMPowerShell.psm1#L193)is where the code starts that enables SSL3 support which was what was supported on our CUCM v9 configuration.

You may have a more updated version of CUCM or configuration of CUCM on the server side that disables SSL3 (which is good) or you might have an older version of CUCM but have policy enforced on your computer that disables SSL3 on your client side.

You could try removing [this line](https://github.com/Tervis-Tumbler/CUCMPowerShell/blob/master/CUCMPowerShell.psm1#L193) and seeing what happens for you by default as this was only needed as a work around due only old ssl support on the version of CUCM we used.

**Comment by JestySam** [comment]
Thank you so much. It worked for me. This is really a great piece of work. Really appreciate you sharing this work to the community.
